language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

git:
  submodules: false

env:
  - TEST_DIR=example/nodejs/
#  - TEST_DIR=tilt-server
before_install: npm install -g jscs babel
script: cd $TEST_DIR && npm install && npm test


#sudo: false

#cache:
#    directories:
#        - node_modules