language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"


env:
  - TEST_DIR=example/nodejs/
#  - TEST_DIR=tilt-server

script: cd $TEST_DIR && npm install && npm test


#sudo: false

#cache:
#    directories:
#        - node_modules