language: node_js

node_js:
    - "4.0"
    - "4.1"
    - "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



env:
    - TEST_DIR=example/nodejs/



before_script:
    # Prepare for automated tests
    - make automated-tests-prepare

    #- npm install -g babel



script:
    # Check version and environment
    - make automated-tests-check

    # Run tests
    - make automated-tests-run



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/eeddc70678354af6584f

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
